version: 1
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'npm'
      - 'dependencies'
    commit-message:
      prefix: 'chore(deps)'
    reviewers:
      - 'SilasRodrigues19'
    assignees:
      - 'SilasRodrigues19'
    open-pull-requests-limit: 10